[package]
name = "iroh-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
iroh = { version = "0.35.0", features = ["discovery-local-network"] }
rand = "0.9.1"
tokio = "1.45.1"
